### ISSUE TITLE
Java 11 compile issues in nightly build

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko#1751]
Happening for a few days. Affects all Java 11 builds but not other Java versions.
Example:
https://github.com/apache/pekko/actions/runs/13000969784/job/36259394315

Very weird ref to scala 3.6.3 in this log.

```
Compiling project (Scala 3.6.3, JVM (11))
[error] ./stream/target/scala-cli/VerifyJDK9Classes-2.12.sc:28:26
[error] Cyclic reference involving val <import>
[error] 
[error]  Run with -explain-cyclic for more details.
[error]     implicit val system: ActorSystem = ActorSystem.create("test")
[error]                          ^
[error] ./stream/target/scala-cli/VerifyJDK9Classes-2.12.sc:22:12
[error] value apache is not a member of org
[error]     import org.apache.pekko.actor.ActorSystem
[error]            ^^^^^^^^^^
[error] ./stream/target/scala-cli/VerifyJDK9Classes-2.12.sc:23:12
[error] value apache is not a member of org
[error]     import org.apache.pekko.stream.scaladsl.{ JavaFlowSupport, Source }
[error]            ^^^^^^^^^^
Error compiling project (Scala 3.6.3, JVM (11))
Compilation failed
Error when verifying stream/target/scala-cli/VerifyJDK9Classes-2.12.sc.
Error: Process completed with exit code 1.
```

Nightly build has an extra section that only runs with Java 11. So this issue is probably not Java 11 specific.

https://github.com/apache/pekko/blob/main/.github/workflows/nightly-builds.yml#L205-L217

**Comment by pjfanning** [comment]
Last time this passed on Java 11, we had:

```
Scala CLI version: 1.5.4
Scala version (default): 3.5.2
```

**Comment by tgodzik** [comment]
Does it happen with `--server=false` or works with Scala CLI 1.6.1 and Scala 3.5.2 ?

**Comment by He-Pin** [comment]
It works before , but starting failing after scala cli 1.6.3 released, I don't have my PC by my side for now.

**Comment by pjfanning** [comment]
@gedochao found the issue in https://github.com/VirtusLab/scala-cli/issues/3464

The license header breaks the script with scala-cli 1.6.1. It now must appear after the using directives.

**Comment by pjfanning** [comment]
@He-Pin I don't think the verify jdk9 script is being run - I think it just compiling the code. The println of the result that appears in the script does not lead to a result being printed in the CI logs.

This is a pre-existing issue. Nothing to do with the scala-cli change that caused the compile to stop working.
