### ISSUE TITLE
ClusterSharding must initialize cluster and allocate sharded actors

### ISSUE THREAD

**Issue by raboof** [apache/pekko#2476]
```
<-- [ClusterSharding must initialize cluster and allocate sharded actors] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for 1)]
[11-10 22:43:04.766] [info] - must initialize cluster and allocate sharded actors *** FAILED *** (10 seconds, 235 milliseconds)
[11-10 22:43:04.766] [info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for 1
[11-10 22:43:04.766] [info]   at scala.Predef$.assert(Predef.scala:279)
[11-10 22:43:04.766] [info]   at org.apache.pekko.testkit.TestKitBase.expectMsg_internal(TestKit.scala:470)
[11-10 22:43:04.766] [info]   at org.apache.pekko.testkit.TestKitBase.expectMsg(TestKit.scala:447)
[11-10 22:43:04.766] [info]   at org.apache.pekko.testkit.TestKitBase.expectMsg$(TestKit.scala:447)
[11-10 22:43:04.767] [info]   at org.apache.pekko.testkit.TestKit.expectMsg(TestKit.scala:963)
[11-10 22:43:04.767] [info]   at org.apache.pekko.cluster.sharding.ShardRegionSpec.$anonfun$new$2(ShardRegionSpec.scala:173)
[11-10 22:43:04.767] [info]   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
[11-10 22:43:04.767] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[11-10 22:43:04.767] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[11-10 22:43:04.767] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[11-10 22:43:04.767] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[11-10 22:43:04.767] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[11-10 22:43:04.767] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[11-10 22:43:04.767] [info]   at org.apache.pekko.testkit.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:46)
[11-10 22:43:04.767] [info]   at org.apache.pekko.testkit.EventFilter.intercept(TestEventListener.scala:128)
[11-10 22:43:04.767] [info]   at org.apache.pekko.testkit.WithLogCapturing.withFixture(WithLogCapturing.scala:44)
[11-10 22:43:04.767] [info]   at org.apache.pekko.testkit.WithLogCapturing.withFixture$(WithLogCapturing.scala:31)
[11-10 22:43:04.767] [info]   at org.apache.pekko.cluster.sharding.ShardRegionSpec.withFixture(ShardRegionSpec.scala:109)
[11-10 22:43:04.767] [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
[11-10 22:43:04.767] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
[11-10 22:43:04.767] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[11-10 22:43:04.767] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
[11-10 22:43:04.767] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1232)
[11-10 22:43:04.767] [info]   at org.apache.pekko.testkit.PekkoSpec.runTest(PekkoSpec.scala:82)
[11-10 22:43:04.767] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1309)
[11-10 22:43:04.767] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[11-10 22:43:04.767] [info]   at scala.collection.immutable.List.foreach(List.scala:323)
[11-10 22:43:04.767] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[11-10 22:43:04.768] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[11-10 22:43:04.768] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[11-10 22:43:04.768] [info]   at scala.collection.immutable.List.foreach(List.scala:323)
[11-10 22:43:04.768] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[11-10 22:43:04.768] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[11-10 22:43:04.768] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[11-10 22:43:04.768] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1309)
[11-10 22:43:04.768] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1308)
[11-10 22:43:04.768] [info]   at org.apache.pekko.testkit.PekkoSpec.runTests(PekkoSpec.scala:82)
[11-10 22:43:04.768] [info]   at org.scalatest.Suite.run(Suite.scala:1114)
[11-10 22:43:04.768] [info]   at org.scalatest.Suite.run$(Suite.scala:1096)
[11-10 22:43:04.768] [info]   at org.apache.pekko.testkit.PekkoSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(PekkoSpec.scala:82)
[11-10 22:43:04.768] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1354)
[11-10 22:43:04.768] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[11-10 22:43:04.768] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1354)
[11-10 22:43:04.768] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1352)
[11-10 22:43:04.768] [info]   at org.apache.pekko.testkit.PekkoSpec.org$scalatest$BeforeAndAfterAll$$super$run(PekkoSpec.scala:82)
[11-10 22:43:04.768] [info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[11-10 22:43:04.768] [info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[11-10 22:43:04.768] [info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[11-10 22:43:04.768] [info]   at org.apache.pekko.testkit.PekkoSpec.run(PekkoSpec.scala:82)
[11-10 22:43:04.768] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[11-10 22:43:04.768] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[11-10 22:43:04.768] [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
[11-10 22:43:04.768] [info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[11-10 22:43:04.768] [info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11-10 22:43:04.768] [info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11-10 22:43:04.768] [info]   at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by pjfanning** [comment]
@raboof I don't think this flaky - I think it now just broken by #2462 - I will revert that

**Comment by pjfanning** [comment]
```
Uncaught error from thread [ShardRegionSpec-pekko.cluster.distributed-data.durable.pinned-store-26]: Could not initialize class org.lmdbjava.Library, shutting down JVM since 'pekko.jvm-exit-on-fatal-error' is enabled for ActorSystem[ShardRegionSpec]
java.lang.NoClassDefFoundError: Could not initialize class org.lmdbjava.Library
	at org.lmdbjava.Env$Builder.open(Env.java:544)
	at org.lmdbjava.Env$Builder.open(Env.java:569)
	at org.apache.pekko.cluster.ddata.LmdbDurableStore.org$apache$pekko$cluster$ddata$LmdbDurableStore$$lmdb(DurableStore.scala:157)
	at org.apache.pekko.cluster.ddata.LmdbDurableStore$$anonfun$active$1.applyOrElse(DurableStore.scala:253)
	at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:548)
	at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:546)
	at org.apache.pekko.cluster.ddata.LmdbDurableStore.aroundReceive(DurableStore.scala:125)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:589)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:556)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:271)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:232)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /tmp/lmdbjava-native-library-16392340801923603006.so)
Library names
[/tmp/lmdbjava-native-library-16392340801923603006.so]
```

**Comment by raboof** [comment]
Indeed looks fixed with #2483
